# Generated by Django 4.2.4 on 2023-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(null=True)),
                ('quantity_ordered', models.IntegerField(blank=True, null=True)),
                ('price_each', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_line_number', models.IntegerField(blank=True, null=True)),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_date', models.CharField(default=None, max_length=50)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('qtr_id', models.IntegerField(blank=True, null=True)),
                ('month_id', models.IntegerField(blank=True, null=True)),
                ('year_id', models.IntegerField(blank=True, null=True)),
                ('product_line', models.CharField(blank=True, max_length=255, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('territory', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deal_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
