# Generated by Django 4.2.4 on 2023-09-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity_ordered', models.IntegerField()),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_line_number', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('qtr_id', models.IntegerField()),
                ('month_id', models.IntegerField()),
                ('year_id', models.IntegerField()),
                ('product_line', models.CharField(max_length=255)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('territory', models.CharField(max_length=255)),
                ('contact_last_name', models.CharField(max_length=255)),
                ('contact_first_name', models.CharField(max_length=255)),
                ('deal_size', models.CharField(max_length=255)),
            ],
        ),
    ]
