# Generated by Django 4.2.4 on 2023-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_data_science', '0002_order_id_alter_order_address_line1_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
