# Generated by Django 4.2.4 on 2023-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='subject',
            field=models.CharField(default='Subject', max_length=155),
            preserve_default=False,
        ),
    ]
