# Generated by Django 4.2.4 on 2023-08-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('website', models.URLField()),
                ('company_address_line_1', models.CharField(max_length=200, null=True)),
                ('company_address_line_2', models.CharField(max_length=200, null=True)),
                ('company_city', models.CharField(max_length=200, null=True)),
                ('company_state', models.CharField(max_length=200, null=True)),
                ('company_zip', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_customer', models.BooleanField(default=False)),
                ('customer_type', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('initial_email', models.DateTimeField(auto_now_add=True)),
                ('date_last_contacted', models.DateTimeField(auto_now_add=True)),
                ('source_of_lead', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lead_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
