# Generated by Django 4.2.4 on 2023-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='business',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='response',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_choice',
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
