# Generated by Django 4.2.4 on 2023-08-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_radio',
            field=models.BooleanField(default=False),
        ),
    ]
