# Generated by Django 4.2.4 on 2023-08-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_business_response_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='email',
        ),
        migrations.RemoveField(
            model_name='response',
            name='name',
        ),
        migrations.RemoveField(
            model_name='response',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='survey',
            name='business_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
