# Generated by Django 4.2.4 on 2023-08-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_is_radio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='response',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ManyToManyField(to='survey.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='selected_choice',
            field=models.ManyToManyField(to='survey.choice'),
        ),
    ]
